### ISSUE TITLE
Extension's marketplace page shows mermaid screenshot instead of check box example

### ISSUE THREAD

**Issue by sergiivolchkov** [mjbvz/vscode-markdown-checkboxes#1]
The [page at marketplace](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox#overview) refers to mermaid extension screenshot:
![Screenshot of Mermaid](https://github.com/mjbvz/vscode-markdown-mermaid/raw/master/docs/example.png)

**Comment by mjbvz** [comment]
Thanks. Fixed in 0.0.5
