### ISSUE TITLE
Does this extension have settings?

### ISSUE THREAD

**Issue by usernamehw** [mjbvz/vscode-markdown-checkboxes#11]
https://github.com/mjbvz/vscode-markdown-checkboxes/blob/dc0e4c433c76eff9b56da4e69ae1de6ddcf17a5f/package.json#L30-L55

They are not present in Settings UI or settings.json.

**Comment by VictorColomb** [comment]
As of 0.3.2, for me at least, searching for `@ext:bierner.markdown-checkbox` in the VS Code settings displays the 3 settings.

**Comment by usernamehw** [comment]
It does.
