### ISSUE TITLE
Any chance of Notebook support?

### ISSUE THREAD

**Issue by MaverickMartyn** [mjbvz/vscode-markdown-checkboxes#15]
Any chance this could be added to the markdown parser for VS Code notebooks?
I'd love to have checklist support in those. Even more so if the could be made clickable for easy toggling.
I haven't had time to look into it, so I presently have no clue how difficult this would be to implement.

**Comment by MaverickMartyn** [comment]
Is this abandonware, or are you just too busy?

**Comment by mjbvz** [comment]
@MaverickMartyn Please submit a pr if you want this fixed
