### ISSUE TITLE
Checkboxes misaligned

### ISSUE THREAD

**Issue by McPrescott** [mjbvz/vscode-markdown-checkboxes#2]
Running VS Code on Ubuntu 16.04. The check boxes and list items are not aligned well.

![screenshot from 2018-01-10 16-07-56](https://user-images.githubusercontent.com/20735042/34800801-a5b1c676-f622-11e7-8124-e66423f8dd0b.png)

**Comment by mjbvz** [comment]
The bug is that both the list bullets and the checkboxes are showing, correct?

**Comment by McPrescott** [comment]
I wouldn't mind if both were showing; if the bullets were hidden that would solve the problem though. I just don't like the vertical alignment of the checkbox. In the image you can see that the bottom of the checkbox is aligned with the bullet and is also above the bottom of the text. I would prefer if it were centered; either the checkbox be vertically centered with the bullet, or the bottom of the checkbox be aligned with the bottom of the text. I'm not sure if that was an intentional design or not. I could fix using a custom stylesheet for markdown, but I thought that it was probably a bug.

I apologize for being unclear in the original comment.

**Comment by mjbvz** [comment]
Fixed by c15d64f5d03837e0099c001fad524cf60ecf4426
