### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by pdagobert** [mjbvz/vscode-markdown-checkboxes#3]
Nesteds lists doesn't render correctly :

![code_2018-02-01_14-57-03](https://user-images.githubusercontent.com/19287463/35682226-31016a80-0760-11e8-8c13-f163fe76e5a3.png)

Instead of :

![firefox_2018-02-01_14-51-26](https://user-images.githubusercontent.com/19287463/35682152-f84d704e-075f-11e8-87f3-9b81e11a2e42.png)

**Comment by mjbvz** [comment]
Thanks. Fixed by 0c93304

Published as 0.1.1
