### ISSUE TITLE
Is it possible not to display the bulletpoints before the checkboxes?

### ISSUE THREAD

**Issue by GhostLyrics** [mjbvz/vscode-markdown-checkboxes#4]
If it is not - which is completely okay - it should be documented, e.g. in the readme.

Thank you for your helpful extension. :)

**Comment by mjbvz** [comment]
Extension should already do this:

![screen shot 2018-06-13 at 11 49 54 am](https://user-images.githubusercontent.com/12821956/41371666-ecc267fe-6eff-11e8-8af6-6aea693152a5.png)
